# Concert2Studio Configuration
# All hyperparameters, paths, and toggle flags

# Data Configuration
data:
  data_dir: "./data"
  sample_rate: 48000  # Standard rate for better compatibility
  bit_depth: 24
  train_split: 0.9
  val_split: 0.1
  random_seed: 42
  use_synthetic: false  # Disable synthetic data to prevent overfitting

# Audio Processing
audio:
  segment_length: 4.0  # seconds
  n_fft: 1024
  hop_length: 256
  win_length: 1024
  window: "hann"

# Model Architecture
model:
  # Spectrogram U-Net (optimized for 16 samples)
  unet:
    in_channels: 1  # Single channel magnitude spectrogram
    base_channels: 16  # Heavily reduced for small dataset
    max_channels: 128  # Heavily reduced
    n_blocks: 3  # Minimal architecture
    dilations: [1, 2, 4]  # Simplified
    use_attention: false  # Disabled to reduce params
    attention_heads: 1
    dropout: 0.2  # Strong regularization

  # UnivNet Vocoder
  use_vocoder: true  # Set to false to bypass vocoder for debugging
  vocoder:
    model_name: "univnet-c32"
    pretrained: true
    freeze_epochs: 5

# Training Configuration (optimized for small dataset)
training:
  batch_size: 4  # Smaller batches for better generalization
  num_epochs: 50  # Reduced to prevent overfitting
  learning_rate: 5e-5  # Much lower learning rate for stability
  weight_decay: 1e-2  # Strong regularization
  beta1: 0.9  # Standard Adam parameters
  beta2: 0.999
  warmup_steps: 100  # Shorter warmup for small dataset
  early_stopping_patience: 8  # Earlier stopping
  gradient_accumulation_steps: 2  # Effective batch size 8
  max_grad_norm: 0.5  # Gradient clipping

# Loss Configuration (simplified for stability)
loss:
  l1_weight: 0.7  # Dominant reconstruction loss
  multires_stft_weight: 0.2  # Reduced spectral loss
  vggish_weight: 0.0  # Disabled heavy perceptual loss
  adversarial_weight: 0.0  # Disabled for stability

  # Multi-resolution STFT scales (reduced for stability)
  stft_scales: [512, 1024, 2048]

# Data Augmentation
augmentation:
  gain_jitter_db: 3.0
  gain_jitter_prob: 1.0
  pink_noise_prob: 0.2
  pink_noise_level: -40  # dB
  time_shift_ms: 50
  time_shift_prob: 0.8

# Checkpointing and Logging
checkpoint:
  save_interval_minutes: 15
  save_interval_steps: 500
  max_checkpoints: 5
  resume_from: null  # path to checkpoint to resume from

# Hardware Configuration
hardware:
  num_workers: 8
  pin_memory: true
  persistent_workers: true
  compile_model: false  # Disabled to avoid CUDA compilation issues
  channels_last: false  # Not applicable to audio models

# Paths
paths:
  output_dir: "./outputs"
  checkpoint_dir: "./checkpoints"
  log_dir: "./logs"
